### ISSUE TITLE
解压到python安装的根目录下即可 如何理解。。。

### ISSUE THREAD

**Issue by shuangwei-Ye** [312885991/seckill_tools#6]
Mac端python的安装路径好像不允许拉进去。。。

**Comment by 312885991** [comment]
与python.exe同目录下





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "312885991/seckill_tools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月24日(星期三) 上午9:55
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [312885991/seckill_tools] 解压到python安装的根目录下即可 如何理解。。。 (Issue #6)





 
Closed #6 as completed.

**Comment by shuangwei-Ye** [comment]
> 与python.exe同目录下
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "312885991/seckill_tools" ***@***.***&gt;; 发送时间:&nbsp;2022年8月24日(星期三) 上午9:55 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;Re: [312885991/seckill_tools] 解压到python安装的根目录下即可 如何理解。。。 (Issue #6) Closed #6 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

我发现...Mac端跑起来 终端只会开启抢的按钮。 像时间设置，平台设置 UI 都不存在。全黑。

**Comment by 312885991** [comment]
买不起mac，没测试过
&nbsp;




刘路生
学生
湖北大学微门户


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月25日(星期四) 上午10:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [312885991/seckill_tools] 解压到python安装的根目录下即可 如何理解。。。 (Issue #6)





  
与python.exe同目录下
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "312885991/seckill_tools" @.&gt;; 发送时间:&nbsp;2022年8月24日(星期三) 上午9:55 @.&gt;; @.&gt;; 主题:&nbsp;Re: [312885991/seckill_tools] 解压到python安装的根目录下即可 如何理解。。。 (Issue #6) Closed #6 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
我发现...Mac端跑起来 终端只会开启抢的按钮。 像时间设置，平台设置 UI 都不存在。全黑。
